# Generated by Django 5.2.6 on 2025-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_role_user_roles_alter_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("url", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="accounts.module"
            ),
        ),
    ]
