# Generated by Django 5.2.6 on 2025-10-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_module_role_modules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="description",
        ),
    ]
