from .pangkat_golongan import *
from .jabatan_fungsional import *
from .program_studi import *
from .fakultas import *
from .bidang_kepakaran import *
from .tahun import *
from .sumber_dana import *
from .kabupaten_kota import *
from .karya_ilmiah import *
from .provinsi import *
from .indeksasi import *
from .penerbit import *
from .jenis_kolaborasi import *
from .kelompok_keilmuan import *