from .pangkat_golongan import *
from .jabatan_fungsional import *
from .program_studi import *
from .fakultas import *
from .bidang_kepakaran import *
from .tahun import *
from .sumber_dana import *
from .kabupaten_kota import *
from .provinsi import *
from .jenis_publikasi import *
from .penerbit import *