# Generated by Django 5.2.6 on 2025-11-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nomor_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto_profil', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('angkatan', models.IntegerField()),
                ('program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.programstudi')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gelar_depan', models.CharField(blank=True, max_length=20, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=20, null=True)),
                ('bidang_kepakaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.bidangkepakaran')),
                ('jabatan_fungsional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jabatanfungsional')),
                ('pangkat_golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.pangkatgolongan')),
                ('program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.programstudi')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pangkat_golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.pangkatgolongan')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
