# Generated by Django 5.2.6 on 2025-10-24 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang_kepakaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.bidangkepakaran'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='jabatan_fungsional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jabatanfungsional'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='pangkat_golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.pangkatgolongan'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.programstudi'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.programstudi'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='pangkat_golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.pangkatgolongan'),
        ),
    ]
