# Generated by Django 5.2.6 on 2025-10-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_dosen_bidang_kepakaran_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nama',
            new_name='name',
        ),
    ]
