# Generated by Django 5.2.6 on 2025-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0002_remove_penelitian_tahun_kegiatan_and_more'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tahun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(max_length=10, unique=True)),
                ('tahun', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TahunKegiatan',
        ),
    ]
