# Generated by Django 5.2.6 on 2025-10-25 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_tahun_delete_tahunkegiatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kabupatenkota',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='provinsi',
            old_name='nama',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tahun',
            name='tahun',
        ),
        migrations.AddField(
            model_name='programstudi',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.fakultas'),
        ),
        migrations.AddField(
            model_name='tahun',
            name='name',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tahun',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
