# Generated by Django 5.2.6 on 2025-11-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Level hierarki jabatan (1=tertinggi(cth: rektor))', null=True),
        ),
    ]
