# Generated by Django 5.2.6 on 2025-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_rename_nama_kabupatenkota_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKolaborasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='KelompokRiset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
