from .penelitian_service import *
from .pengabdian_service import *
from .publikasi_service import *
from .dokumen_service import *
from .kegiatan_service import *
from .strategic_source_service import *
from .strategic_goal_service import *
from .strategic_objective_service import *
from .strategic_action_service import *
from .strategic_service import *