# Generated by Django 5.2.6 on 2025-11-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('jumlah_dana', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='penelitian_diikuti', to='people.person')),
                ('jenis_kolaborasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jeniskolaborasi')),
                ('kelompok_keilmuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kelompokkeilmuan')),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penelitian_dipimpin', to='people.person')),
                ('sumber_dana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.sumberdana')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun')),
            ],
        ),
        migrations.CreateModel(
            name='Pengabdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('jumlah_dana', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='pengabdian_diikuti', to='people.person')),
                ('jenis_kolaborasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jeniskolaborasi')),
                ('kelompok_keilmuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kelompokkeilmuan')),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengabdian_dipimpin', to='people.person')),
                ('lokasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kabupatenkota')),
                ('sumber_dana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.sumberdana')),
                ('tahun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun')),
            ],
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('no_regis', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='publikasi_diikuti', to='people.person')),
                ('indeksasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.indeksasi')),
                ('kelompok_keilmuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kelompokkeilmuan')),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publikasi_dipimpin', to='people.person')),
                ('penerbit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.penerbit')),
                ('tahun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun')),
            ],
        ),
    ]
