# Generated by Django 5.2.6 on 2025-10-23 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('jumlah_dana', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('peneliti', models.ManyToManyField(blank=True, related_name='penelitian', to='people.person')),
                ('sumber_dana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.sumberdana')),
                ('tahun_kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahunkegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengabdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('jumlah_dana', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('lokasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kabupatenkota')),
                ('pengabdi', models.ManyToManyField(blank=True, related_name='pengabdian', to='people.person')),
                ('tahun_kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahunkegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('no_regis', models.CharField(blank=True, max_length=150, null=True)),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('jenis_publikasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jenispublikasi')),
                ('penerbit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.penerbit')),
                ('penulis', models.ManyToManyField(blank=True, related_name='publikasi', to='people.person')),
                ('tahun_kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahunkegiatan')),
            ],
        ),
    ]
