# Generated by Django 5.2.6 on 2025-11-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0001_initial'),
        ('references', '0002_karyailmiah'),
    ]

    operations = [
        migrations.AddField(
            model_name='publikasi',
            name='karya_ilmiah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.karyailmiah'),
        ),
    ]
