# Generated by Django 5.2.6 on 2025-10-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian',
            name='tahun_kegiatan',
        ),
        migrations.RemoveField(
            model_name='pengabdian',
            name='tahun_kegiatan',
        ),
        migrations.RemoveField(
            model_name='publikasi',
            name='tahun_kegiatan',
        ),
    ]
