# Generated by Django 5.2.6 on 2025-11-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0002_publikasi_karya_ilmiah'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('strategic_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='lppm.strategicgoal')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('current', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('all_year', models.JSONField(blank=True, default=dict, null=True)),
                ('yearly_data', models.JSONField(blank=True, default=list, null=True)),
                ('filter_keyword', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('strategic_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lppm.strategicobjective')),
                ('strategic_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='lppm.strategicsource')),
            ],
        ),
    ]
