# Generated by Django 5.2.6 on 2025-10-24 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0002_remove_penelitian_tahun_kegiatan_and_more'),
        ('references', '0002_tahun_delete_tahunkegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='tahun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun'),
        ),
        migrations.AddField(
            model_name='pengabdian',
            name='tahun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun'),
        ),
        migrations.AddField(
            model_name='publikasi',
            name='tahun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun'),
        ),
    ]
