# Generated by Django 5.2.6 on 2025-10-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0003_penelitian_tahun_pengabdian_tahun_publikasi_tahun'),
        ('people', '0003_rename_nama_person_name'),
        ('references', '0004_jeniskolaborasi_kelompokriset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian',
            name='peneliti',
        ),
        migrations.AddField(
            model_name='penelitian',
            name='anggota_peneliti',
            field=models.ManyToManyField(blank=True, null=True, related_name='penelitian_diikuti', to='people.person'),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='jenis_kolaborasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.jeniskolaborasi'),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='kelompok_riset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.kelompokriset'),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='ketua_peneliti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penelitian_dipimpin', to='people.person'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='sumber_dana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.sumberdana'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='tahun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun'),
        ),
    ]
