# Generated by Django 5.2.6 on 2025-11-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0003_strategicgoal_strategicsource_strategicobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicaction',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
