# Generated by Django 5.2.6 on 2025-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0004_strategicaction_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicaction',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
