# Generated by Django 5.2.6 on 2025-11-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lppm', '0005_alter_strategicaction_unit'),
        ('references', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('kriteria_terkait', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('Tersedia', 'Tersedia'), ('Dalam Proses', 'Dalam Proses'), ('Belum Ada', 'Belum Ada')], max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('tahun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun')),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('tempat', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('Terjadwal', 'Terjadwal'), ('Terlaksana', 'Terlaksana'), ('Dibatalkan', 'Dibatalkan')], max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengabdian_pj', to='references.position')),
                ('tahun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.tahun')),
            ],
        ),
    ]
